# Generated by Django 4.1.6 on 2023-02-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', help_text='127 symbols max', max_length=127, verbose_name='username'),
        ),
    ]
