# Generated by Django 4.1.6 on 2023-02-13 19:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='name')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'default_related_name': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='name')),
                ('main_picture', models.ImageField(blank=True, upload_to='images/%Y/%m', verbose_name='post picture')),
                ('title', models.TextField(blank=True, help_text='Заголовок поста', max_length=120, verbose_name='title')),
                ('text', tinymce.models.HTMLField(blank=True, help_text='Основной текст поста', verbose_name='description')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='datetime of post creation', verbose_name='created on')),
                ('views', models.PositiveIntegerField(blank=True, default=0, verbose_name='views')),
                ('tags', models.ManyToManyField(help_text='Post tags', to='homepage.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'default_related_name': 'posts',
            },
        ),
    ]
