# Generated by Django 4.1.6 on 2023-02-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, help_text='Заголовок поста', max_length=120, verbose_name='title'),
        ),
    ]
