# Generated by Django 4.1.6 on 2023-02-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='', help_text='Введите краткое описание', max_length=150, verbose_name='Краткое описание'),
        ),
    ]
